class MyException(Exception):
    def __int__(self,msg):
        pass